version: '3'

services:
  todo-server:
    build: ./provisioning
    container_name: todo-server
    image: laravel-todo
    depends_on:
      - mysql
      - mysql-test
      - redis
    volumes:
      - ./:/application:cached

  queue-server:
    build: ./provisioning
    image: laravel-todo
    command: php artisan queue:work
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql
    container_name: todo-mysql
    ports:
      - '3315:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=laravel-todo
    volumes:
      - ./storage/tmp/db:/var/lib/mysql:cached
    command: --default-authentication-plugin=mysql_native_password

  mysql-test:
    image: mysql
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=testing

  nginx:
    image: nginx
    ports:
      - '8000:8000'
    volumes:
      - ./provisioning/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./public:/application/public:cached
    depends_on:
      - todo-server

  redis:
    image: redis
    ports:
      - '127.0.0.4:6379:6379'

  echo-server:
    image: node
    ports:
      - 8888:8888
    working_dir: /application
    volumes:
      - .:/application:cached
    depends_on:
      - redis
      - todo-server
    command: 'npm start'